version: '3.7'

services:
  fastapi:
    build: .
    restart: always
    volumes:
      - ./code/app:/home/keys4/app
    ports:
      - 5000:5000
    environment:
      - DEBUG=0

        #  nginx:
        #    image: nginx
        #    volumes:
        #      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        #      - ./nginx/certs:/etc/nginx/certs
        #    ports:
        #      - 80:80
        #      - 443:443
        #    depends_on:
        #      - fastapi
